### PR TITLE
Jre17 but *smol*

### PR DESCRIPTION
**Pull request by Mathias-Boulay**
This pull request is a bit like #7.

Features:
- Smaller runtime size, via proper use of jlink to create a jre equivalent of the jdk. I believe it could be reduced further.
- Bundled runtime support, jre17-pojav weighs [~36MB](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/2220042085) **[REQUIRES TESTING]**

This could allow to *~~make pojav fat again~~* fit both important runtimes within the apk, for a more user friendly experience.

### CODE REVIEW

**Comment by ghost** [comment]
Corrupted Java Runtime aarch64

**Comment by ghost** [comment]
The aarch64 build contain arm64 one instead of aarch64, why lying ?

**Comment by unilock** [comment]
> The aarch64 build contain arm64 one instead of aarch64, why lying ?

aarch64 = arm64...

**Comment by Hangouts34** [comment]
Hết hạng r

**Pull request merged**
