### PR TITLE
Fix fPIE requirement 

### PR DESCRIPTION
**Pull request by SolDev69**
Fixes termux support for jre8

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
It doesn't seem to affect the executables under the bin directory.
Tried with the unpack200 executable on arm, but got an issue related to the lack of position-independent code upon execution

**Comment by Parsa307** [comment]
uwu

**Comment by Parsa307** [comment]
uwu

**Comment by Hossishash** [comment]
Gg

**Pull request closed without merging**
